### ISSUE TITLE
docker run masif_ligand/data_prepare_one.sh meets error OSError: File not found: data_preparation/01-benchmark_surfaces//4ZQK_A.ply

### ISSUE THREAD

**Issue by Lizeerd** [LPDI-EPFL/masif#47]
i tried the script in docker, ./masif_ligand/data_prepare_one.sh 4ZQK_A
and gets the following error
Downloading PDB structure '4ZQK'...
Traceback (most recent call last):
  File "/masif/source//data_preparation/00b-generate_assembly.py", line 3, in <module>
    from SBI.structure import PDB
ImportError: No module named SBI.structure
Traceback (most recent call last):
  File "/masif/source//data_preparation/00c-save_ligand_coords.py", line 2, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/masif/source//data_preparation/01-pdb_extract_and_triangulate.py", line 48, in <module>
    extractPDB(pdb_filename, out_filename1+".pdb", chain_ids1)
  File "/masif/source/input_output/extractPDB.py", line 21, in extractPDB
    model = Selection.unfold_entities(struct, "M")[0]
IndexError: list index out of range
4ZQK_A
Reading data from input ply surface files.
Traceback (most recent call last):
  File "/masif/source//data_preparation/04-masif_precompute.py", line 74, in <module>
    input_feat[pid], rho[pid], theta[pid], mask[pid], neigh_indices[pid], iface_labels[pid], verts[pid] = read_data_from_surface(ply_file[pid], params)
  File "/masif/source/masif_modules/read_data_from_surface.py", line 23, in read_data_from_surface
    mesh = pymesh.load_mesh(ply_fn)
  File "/usr/local/lib/python3.6/site-packages/pymesh/meshio.py", line 21, in load_mesh
    raise IOError("File not found: {}".format(filename));
OSError: File not found: data_preparation/01-benchmark_surfaces//4ZQK_A.ply

can anyone tell me where i got wrong, thx

**Comment by huanggewudi** [comment]
Is it solved?

**Comment by brpe7306** [comment]
getting this same error

**Comment by horacehht** [comment]
get the same error

**Comment by Hylouis233** [comment]
The same question
