### ISSUE TITLE
Data processing script is not working

### ISSUE THREAD

**Issue by BSharmi** [LPDI-EPFL/masif#67]
Hi there!

I am getting the following error in MaSIF data processing. I followed the demo example
```
root@dc2aa58b2fb5:/masif/data/masif_site# ./data_prepare_one.sh 4ZQK_A
Downloading PDB structure '4ZQK'...
Desired structure doesn't exists
Empty
pdb filename
/tmp/4ZQK.pdb
Traceback (most recent call last):
  File "/masif/source//data_preparation/01-pdb_extract_and_triangulate_test.py", line 55, in <module>
    extractPDB(pdb_filename, out_filename1+".pdb", chain_ids1)
  File "/masif/source/input_output/extractPDB.py", line 38, in extractPDB
    model = Selection.unfold_entities(struct, "M")[0]
IndexError: list index out of range
4ZQK_A
Reading data from input ply surface files.
Traceback (most recent call last):
  File "/masif/source//data_preparation/04-masif_precompute.py", line 74, in <module>
    input_feat[pid], rho[pid], theta[pid], mask[pid], neigh_indices[pid], iface_labels[pid], verts[pid] = read_data_from_surface(ply_file[pid], params)
  File "/masif/source/masif_modules/read_data_from_surface.py", line 23, in read_data_from_surface
    mesh = pymesh.load_mesh(ply_fn)
  File "/usr/local/lib/python3.6/site-packages/pymesh/meshio.py", line 21, in load_mesh
    raise IOError("File not found: {}".format(filename));
OSError: File not found: data_preparation/01-benchmark_surfaces//4ZQK_A.ply
```

Can someone please help?

Thank you!

**Comment by bukkeshuo** [comment]
> I am getting the following error in MaSIF data processing. I followed the demo example

hello，How did you download reduce? Can you tell me?

**Comment by jche801** [comment]
hello, I encountered same error with you by just following the instruction on Docker tutorial page, have you solve the issue?

**Comment by jche801** [comment]
> Hi there!
> 
> I am getting the following error in MaSIF data processing. I followed the demo example
> 
> ```
> root@dc2aa58b2fb5:/masif/data/masif_site# ./data_prepare_one.sh 4ZQK_A
> Downloading PDB structure '4ZQK'...
> Desired structure doesn't exists
> Empty
> pdb filename
> /tmp/4ZQK.pdb
> Traceback (most recent call last):
>   File "/masif/source//data_preparation/01-pdb_extract_and_triangulate_test.py", line 55, in <module>
>     extractPDB(pdb_filename, out_filename1+".pdb", chain_ids1)
>   File "/masif/source/input_output/extractPDB.py", line 38, in extractPDB
>     model = Selection.unfold_entities(struct, "M")[0]
> IndexError: list index out of range
> 4ZQK_A
> Reading data from input ply surface files.
> Traceback (most recent call last):
>   File "/masif/source//data_preparation/04-masif_precompute.py", line 74, in <module>
>     input_feat[pid], rho[pid], theta[pid], mask[pid], neigh_indices[pid], iface_labels[pid], verts[pid] = read_data_from_surface(ply_file[pid], params)
>   File "/masif/source/masif_modules/read_data_from_surface.py", line 23, in read_data_from_surface
>     mesh = pymesh.load_mesh(ply_fn)
>   File "/usr/local/lib/python3.6/site-packages/pymesh/meshio.py", line 21, in load_mesh
>     raise IOError("File not found: {}".format(filename));
> OSError: File not found: data_preparation/01-benchmark_surfaces//4ZQK_A.ply
> ```
> 
> Can someone please help?
> 
> Thank you!

it seems PDB file can not be downloaded but IDK why

**Comment by aanyouzoa1** [comment]
Hi all,

I am also hitting the same issue.
Did anyone find a solution for this?

Thanks!
