### ISSUE TITLE
masif_site docker tutorial 4ZQk_A error

### ISSUE THREAD

**Issue by seojinleee** [LPDI-EPFL/masif#85]
> Downloading PDB structure '4ZQk'...
> Desired structure doesn't exists
> Empty
> Traceback (most recent call last):
>   File "/masif/source//data_preparation/01-pdb_extract_and_triangulate.py", line 48, in <module>
>     extractPDB(pdb_filename, out_filename1+".pdb", chain_ids1)
>   File "/masif/source/input_output/extractPDB.py", line 38, in extractPDB
>     model = Selection.unfold_entities(struct, "M")[0]
> IndexError: list index out of range
> 4ZQk_A
> Reading data from input ply surface files.
> Traceback (most recent call last):
>   File "/masif/source//data_preparation/04-masif_precompute.py", line 74, in <module>
>     input_feat[pid], rho[pid], theta[pid], mask[pid], neigh_indices[pid], iface_labels[pid], verts[pid] = read_data_from_surface(ply_file[pid], params)
>   File "/masif/source/masif_modules/read_data_from_surface.py", line 23, in read_data_from_surface
>     mesh = pymesh.load_mesh(ply_fn)
>   File "/usr/local/lib/python3.6/site-packages/pymesh/meshio.py", line 21, in load_mesh
>     raise IOError("File not found: {}".format(filename));
> OSError: File not found: data_preparation/01-benchmark_surfaces//4ZQk_A.ply

I'm using docker to reproduce the tutorial results, but I keep on getting this error.
Can someone please help me through this?

**Comment by yanz-24** [comment]
The link for downloading files from the PDB archive is outdated. It should be updated to `https://files.wwpdb.org` at this [line](https://github.com/LPDI-EPFL/masif/blob/2a370518e0d0d0b0d6f153f2f10f6630ae91f149/source/data_preparation/00-pdb_download.py#L27C1-L28C1).

**Comment by tao840813** [comment]
> The link for downloading files from the PDB archive is outdated. It should be updated to `https://files.wwpdb.org` at this [line](https://github.com/LPDI-EPFL/masif/blob/2a370518e0d0d0b0d6f153f2f10f6630ae91f149/source/data_preparation/00-pdb_download.py#L27C1-L28C1).

Thank you so much! It works!

**Comment by leighseismic** [comment]
can I use masif site on things not in the PDB?
